### ISSUE TITLE
Release configuration merges more assemblies when needed

### ISSUE THREAD

**Issue by FixRM** [ravibpatel/ILRepack.Lib.MSBuild.Task#16]
Hello @ravibpatel,

I have the following configuration and it works great for Debug builds:
 ```xml
 <Target Name="AfterBuild">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)\D365Extensions.dll" />
      <InputAssemblies Include="$(OutputPath)\Newtonsoft.Json.dll" />
    </ItemGroup>
    <ILRepack Parallel="true" DebugInfo="true" InputAssemblies="@(InputAssemblies)" KeyFile="$(AssemblyOriginatorKeyFile)" LibraryPath="$(OutputPath)" OutputFile="$(OutputPath)\$(AssemblyName).dll" />
  </Target>
```
as you can see, there is no conditions or something. For some reasons I see the following output for Release build:
1>  SomePlugin -> C:\...\bin\Release\SomePlugin.dll
1>  Added assembly 'bin\Release\\SomePlugin .dll'
1>  Added assembly 'bin\Release\\D365Extensions.dll'
1>  Added assembly 'bin\Release\\Newtonsoft.Json.dll'
1>  Merging 3 assembies to 'bin\Release\\SomePlugin.dll'
1>  Merge succeeded in 0,8986863 s
1>  Added assembly 'bin\Release\\SomePlugin.dll'
1>  Added assembly 'bin\Release\\D365Extensions.dll'
1>  Added assembly 'bin\Release\\Newtonsoft.Json.dll'
1>  Added assembly 'bin\Release\SomePlugin .dll'
1>  Added assembly 'bin\Release\D365Extensions.dll'
1>  Added assembly 'bin\Release\Microsoft.Crm.Sdk.Proxy.dll'
1>  Added assembly 'bin\Release\Microsoft.Xrm.Sdk.dll'
1>  Added assembly 'bin\Release\Microsoft.Xrm.Sdk.Workflow.dll'
1>  Added assembly 'bin\Release\Newtonsoft.Json.dll'
1>  Merging 9 assembies to 'bin\Release\SomePlugin.dll'
1>C:\...\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets(19,5): error : Failed to resolve assembly: 'Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Both Debug and Release configurations are not customized. Any ideas?

**Comment by FixRM** [comment]
Hello? :)

**Comment by ravibpatel** [comment]
Sorry for a very late reply. I was very busy with another project. I think there is a reference still remains for default targets file. Are you providing the target file as "ILRepack.targets" in the project directory?

**Comment by FixRM** [comment]
Not sure if I understand you correctly. Here is my project file:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{04903DB4-F687-4675-89F1-201AAFB61150}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>FixRM.Plugins</RootNamespace>
    <AssemblyName>FixRM.Plugins</AssemblyName>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="D365Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e6d4fbedb179847e, processorArchitecture=MSIL">
      <HintPath>..\packages\D365Extensions.1.0.36\lib\net452\D365Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Crm.Sdk.Proxy, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.12\lib\net462\Microsoft.Crm.Sdk.Proxy.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.12\lib\net462\Microsoft.Xrm.Sdk.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xrm.Sdk.Workflow, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.Workflow.8.2.0.2\lib\net452\Microsoft.Xrm.Sdk.Workflow.dll</HintPath>
    </Reference>
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Activities" />
    <Reference Include="System.Activities.Presentation" />
    <Reference Include="System.Core" />
    <Reference Include="System.DirectoryServices" />
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Web" />
    <Reference Include="System.Workflow.Activities" />
    <Reference Include="System.Workflow.ComponentModel" />
    <Reference Include="System.Workflow.Runtime" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CrmPluginRegistrationAttribute.cs" />
    <Compile Include="PublishAllHandler.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="bin\coretools\CrmSvcUtil.exe.config" />
    <None Include="bin\coretools\LicenseTerms.docx" />
    <None Include="packages.config" />
    <None Include="spkl.json" />
    <None Include="spkl\deploy-plugins.bat" />
    <None Include="spkl\deploy-webresources.bat" />
    <None Include="spkl\deploy-workflows.bat" />
    <None Include="spkl\download-webresources.bat" />
    <None Include="spkl\earlybound.bat" />
    <None Include="spkl\instrument-plugin-code.bat" />
    <None Include="spkl\pack+import.bat" />
    <None Include="spkl\unpack.bat" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\coretools\CrmSvcUtil.exe" />
    <Content Include="bin\coretools\CrmSvcUtil.xml" />
    <Content Include="bin\coretools\Microsoft.Crm.Sdk.Proxy.dll" />
    <Content Include="bin\coretools\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" />
    <Content Include="bin\coretools\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Sdk.Deployment.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Sdk.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.Connector.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.CrmConnectControl.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.Ui.Styles.dll" />
    <Content Include="bin\coretools\Other Redistributable.txt" />
    <Content Include="bin\coretools\SolutionPackager.exe" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="bin\Debug\" />
    <Folder Include="bin\Release\" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets" Condition="Exists('..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets'))" />
  </Target>
  <Target Name="AfterBuild">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)\D365Extensions.dll" />
    </ItemGroup>
    <ILRepack Parallel="true"
              InputAssemblies="@(InputAssemblies)"
              LibraryPath="$(OutputPath)"
              KeyFile="$(AssemblyOriginatorKeyFile)"
              OutputFile="$(OutputPath)\$(AssemblyName).dll" />
  </Target>
</Project>

And here is output for release:

1>------ Build started: Project: Plugins, Configuration: Release Any CPU ------
1>  Plugins -> ---\Plugins\bin\Release\FixRM.Plugins.dll
1>  Added assembly 'bin\Release\\FixRM.Plugins.dll'
1>  Added assembly 'bin\Release\\D365Extensions.dll'
1>  Merging 2 assembies to 'bin\Release\\FixRM.Plugins.dll'
1>  Merge succeeded in 0,1450195 s
1>  Added assembly 'bin\Release\\FixRM.Plugins.dll'
1>  Added assembly 'bin\Release\\D365Extensions.dll'
1>  Added assembly 'bin\Release\FixRM.Plugins.dll'
1>  Added assembly 'bin\Release\D365Extensions.dll'
1>  Added assembly 'bin\Release\Microsoft.Crm.Sdk.Proxy.dll'
1>  Added assembly 'bin\Release\Microsoft.Xrm.Sdk.dll'
1>  Added assembly 'bin\Release\Microsoft.Xrm.Sdk.Workflow.dll'
1>  Merging 7 assembies to 'bin\Release\FixRM.Plugins.dll'
1>---\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets(19,5): error : Duplicate type D365Extensions.CheckParam from D365Extensions.dll, was also present in FixRM.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by FixRM** [comment]
Not sure if I understand you correctly. Here is my project file:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{04903DB4-F687-4675-89F1-201AAFB61150}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>FixRM.Plugins</RootNamespace>
    <AssemblyName>FixRM.Plugins</AssemblyName>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="D365Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e6d4fbedb179847e, processorArchitecture=MSIL">
      <HintPath>..\packages\D365Extensions.1.0.36\lib\net452\D365Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Crm.Sdk.Proxy, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.12\lib\net462\Microsoft.Crm.Sdk.Proxy.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.CoreAssemblies.9.0.2.12\lib\net462\Microsoft.Xrm.Sdk.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xrm.Sdk.Workflow, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.CrmSdk.Workflow.8.2.0.2\lib\net452\Microsoft.Xrm.Sdk.Workflow.dll</HintPath>
    </Reference>
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Activities" />
    <Reference Include="System.Activities.Presentation" />
    <Reference Include="System.Core" />
    <Reference Include="System.DirectoryServices" />
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Web" />
    <Reference Include="System.Workflow.Activities" />
    <Reference Include="System.Workflow.ComponentModel" />
    <Reference Include="System.Workflow.Runtime" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CrmPluginRegistrationAttribute.cs" />
    <Compile Include="PublishAllHandler.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="bin\coretools\CrmSvcUtil.exe.config" />
    <None Include="bin\coretools\LicenseTerms.docx" />
    <None Include="packages.config" />
    <None Include="spkl.json" />
    <None Include="spkl\deploy-plugins.bat" />
    <None Include="spkl\deploy-webresources.bat" />
    <None Include="spkl\deploy-workflows.bat" />
    <None Include="spkl\download-webresources.bat" />
    <None Include="spkl\earlybound.bat" />
    <None Include="spkl\instrument-plugin-code.bat" />
    <None Include="spkl\pack+import.bat" />
    <None Include="spkl\unpack.bat" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\coretools\CrmSvcUtil.exe" />
    <Content Include="bin\coretools\CrmSvcUtil.xml" />
    <Content Include="bin\coretools\Microsoft.Crm.Sdk.Proxy.dll" />
    <Content Include="bin\coretools\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" />
    <Content Include="bin\coretools\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Sdk.Deployment.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Sdk.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.Connector.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.CrmConnectControl.dll" />
    <Content Include="bin\coretools\Microsoft.Xrm.Tooling.Ui.Styles.dll" />
    <Content Include="bin\coretools\Other Redistributable.txt" />
    <Content Include="bin\coretools\SolutionPackager.exe" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="bin\Debug\" />
    <Folder Include="bin\Release\" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets" Condition="Exists('..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets'))" />
  </Target>
  <Target Name="AfterBuild">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)\D365Extensions.dll" />
    </ItemGroup>
    <ILRepack Parallel="true"
              InputAssemblies="@(InputAssemblies)"
              LibraryPath="$(OutputPath)"
              KeyFile="$(AssemblyOriginatorKeyFile)"
              OutputFile="$(OutputPath)\$(AssemblyName).dll" />
  </Target>
</Project>

**Comment by FixRM** [comment]
Hello @ravibpatel, thank you for the reply. It looks like I cant copy paste proj file here, but I can give you a link: https://github.com/FixRM/DuplicateDetectionAlwaysOn/blob/master/DuplicateDetectionAlwaysOn/Plugins/Plugins.csproj.

This is just a basic task setup. I only added `<Target Name="AfterBuild">` as described in doc

**Comment by ravibpatel** [comment]
@FixRM 
Yes, You added your Target directly into your Project file. Rather than doing that I suggest you should make a file named 'ILRepack.targets' in the root directory (Directory where your .csproj file resides) of your project and add your Target inside it.

Please look at the [Usage](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task#usage) section of the documentation.

Feel free to ask if you still encounter any issues.

**Comment by FixRM** [comment]
Thank you for your answer, @ravibpatel. I miss this from doc. But why Debug build work as expected? The second question is can we make Release build works in the same way as I believe that creating additional `.target` files is not very convenient option

**Comment by ravibpatel** [comment]
@FixRM Debug works as expected cause default targets file only executes for Release builds and not for Debug builds. So when you are in Release build both yours and default target runs.

I think creating another target file is a lot better option than adding things to .csproj file directly. Also, I created a default target in such a way that if you provide your target file it will execute only your target file.

**Comment by FixRM** [comment]
Still don't understand... Ok, let it run twice but why it merges different set of assemblies?

**Comment by ravibpatel** [comment]
Default target file looks for dependent assemblies automatically so it is merging everything it finds while you are providing the assemblies manually in your target file.

To remedy the issue you are having I changed it so you can provide your own targets file. You can see #6.

**Comment by FixRM** [comment]
Now I see, there is default target file what is suitable for some projects and it merges every assembly found in build folder... I'm not sure if it was a good idea but now I understand the source of the problem :)

Issue is solved, thank you.

**Comment by chiragknzariya** [comment]
Hello @ravibpatel 

I am getting same error, while merging "Microsoft.Xrm.Sdk" dll.

I have created separate target file as you have suggested above and set "Copy Local" to "FALSE" which excludes specified DLLs from merge.

<script src="https://gist.github.com/chiragknzariya/0dd53f37a5820ee20f12af89a976f303.js"></script>

But still I am getting below error :

**Failed to resolve assembly: 'Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'**

Any help will be appreciated.!

**Comment by FixRM** [comment]
@chiragknzariya, please find sample file here: https://github.com/FixRM/BulletproofProjectTemplate/blob/master/Plugins/ILRepack.targets

**Comment by chiragknzariya** [comment]
Hello @FixRM, my target file is very much similar to your sample file, however I have tried yours but still the same error occurs.

**Comment by FixRM** [comment]
@chiragknzariya, can you try to build my solution? I'm pretty much sure it works.

Key thing to solve problem is to correctly set LibraryPath parameter.

**Comment by chiragknzariya** [comment]
Hi @FixRM , much appreciate your help!

Please find below url for my proj file.
[D365.csproj](https://gist.githubusercontent.com/chiragknzariya/26bac99a1661c82c358d21662f8b0a10/raw/78efc5a0c896461b29cef9dc4f07f38fbed48834/D365.csproj)

I have used https://github.com/FixRM/BulletproofProjectTemplate/blob/master/Plugins/ILRepack.targets.

Error :

:\Users\admin_ck\source\repos\D365.Plugins.New\packages\ILRepack.Lib.MSBuild.Task.2.0.16.1\build\ILRepack.Lib.MSBuild.Task.targets(11,3): error : Failed to resolve assembly: 'Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by FixRM** [comment]
@ @chiragknzariya

**Comment by chiragknzariya** [comment]
Hello @ravibpatel,

I have found the part of the problem and it's because of I am using early bound class file, which uses "[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]".

What do you think could be the problem? Can you please share the solution of the problem.

Thanks

**Comment by siddiquemahsud** [comment]
Hello @ravibpatel ,

**Comment by FixRM** [comment]
Guys, I use provided above config for dozens of projects and it works like a charm. Are you sure your setup is ok?

**Comment by siddiquemahsud** [comment]
I'm using a similar target file (https://github.com/FixRM/D365Extensions), but having the issue
"Failed to resolve assembly: 'Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	"

```
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="AfterBuild">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)\BingMapsRESTToolkit.dll" />
      <InputAssemblies Include="$(OutputPath)\ABC.Common.CRM.dll" />
      <InputAssemblies Include="$(OutputPath)\ABC.Common.CSharp.dll" />
      <InputAssemblies Include="$(OutputPath)\ABC.CRM.Business.dll" />
      <InputAssemblies Include="$(OutputPath)\ABC.CRM.DA.dll" />
      <InputAssemblies Include="$(OutputPath)\ABC.CRM.Services.dll" />
      <InputAssemblies Include="$(OutputPath)\D365Extensions.dll" />
    </ItemGroup> 
    <ILRepack Parallel="true"
             InputAssemblies="@(InputAssemblies)"
             LibraryPath="$(OutputPath)"
             KeyFile="$(AssemblyOriginatorKeyFile)"
             OutputFile="$(OutputPath)\$(AssemblyName).dll" />
  </Target>
</Project>
```
When I was merging the DLLs with ILMerge the namespace Microsoft.Xrm.Sdk.Client was not adding to the output DLL, but here I think the dependency issue is due to Microsoft.Xrm.Sdk.Client, I think the process of merging could not found "Microsoft.Xrm.Sdk.Client" in D365Extensions. Please help if this make sense.

**Comment by FixRM** [comment]
Your config look good... I guess you can try adding each assembly one by one to check if one particular assembly cause the problem. May be there are a circular dependencies or something similar out there?

**Comment by chiragknzariya** [comment]
[Build and package plug-in code](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/build-and-package
)
